import type { Zone } from './types';

export const SKYLIFT: Zone = {
  id: 'skylift',
  name: 'South · Broken Sky Lift',
  entryRequires: [],
  bounds: { min: [-110, -8, -410], max: [110, 130, -70] },
  discoveryRadius: 170,
  warpPoint: [0, 4, -350],
  platforms: [
    {
      id: 'skylift-causeway',
      kind: 'platform',
      position: [0, -1, -100],
      size: [34, 2, 60],
      accent: 'cyan',
    },
    {
      id: 'skylift-ground',
      kind: 'platform',
      position: [0, -1, -255],
      size: [220, 2, 250],
      accent: 'cyan',
    },
    {
      id: 'skylift-ramp-1',
      kind: 'ramp',
      position: [-24, 2.2, -160],
      size: [34, 1, 14],
      rotation: [0, 0, -0.12],
      accent: 'magenta',
    },
    {
      id: 'skylift-ramp-2',
      kind: 'ramp',
      position: [24, 4.8, -188],
      size: [34, 1, 14],
      rotation: [0, 0, 0.12],
      accent: 'cyan',
    },
    {
      id: 'skylift-deck-1',
      kind: 'platform',
      position: [-42, 7, -235],
      size: [34, 2, 28],
      accent: 'magenta',
    },
    {
      id: 'skylift-deck-2',
      kind: 'platform',
      position: [38, 12, -260],
      size: [38, 2, 26],
      accent: 'cyan',
    },
    {
      id: 'skylift-deck-3',
      kind: 'platform',
      position: [-30, 18, -292],
      size: [34, 2, 24],
      accent: 'yellow',
    },
    {
      id: 'skylift-sanctuary-deck',
      kind: 'platform',
      position: [0, 1, -358],
      size: [64, 4, 40],
      accent: 'yellow',
    },
  ],
  landmark: {
    id: 'landmark-skylift',
    name: 'Broken Sky Lift',
    kind: 'skyLift',
    position: [0, 0, -310],
    scale: [54, 118, 48],
    topRequires: ['dash'],
  },
  shards: [
    { id: 'shard-skylift-01', position: [0, 1.5, -92], requires: [] },
    { id: 'shard-skylift-02', position: [-18, 1.5, -136], requires: [] },
    { id: 'shard-skylift-03', position: [32, 1.5, -170], requires: [] },
    { id: 'shard-skylift-04', position: [-58, 1.5, -202], requires: [] },
    { id: 'shard-skylift-05', position: [-42, 9, -235], requires: [] },
    { id: 'shard-skylift-06', position: [38, 14, -260], requires: [] },
    { id: 'shard-skylift-07', position: [-30, 20, -292], requires: ['dash'] },
    { id: 'shard-skylift-08', position: [62, 1.5, -310], requires: ['dash'] },
    { id: 'shard-skylift-09', position: [-45, 1.5, -352], requires: ['dash'] },
    { id: 'shard-skylift-10', position: [22, 4.5, -372], requires: ['dash'] },
  ],
  steles: [
    { id: 'stele-skylift-01', position: [26, 2.5, -128], requires: [] },
    { id: 'stele-skylift-02', position: [-68, 2.5, -276], requires: [] },
    {
      id: 'stele-skylift-03',
      position: [18, 3.5, -360],
      requires: ['dash'],
    },
  ],
  sanctuary: {
    id: 'sanctuary-dash',
    position: [0, 4, -374],
    requires: [],
    grants: 'dash',
  },
};
